services:
  db:
    image: postgres:16-alpine
    container_name: study-platform-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: study-platform-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root189065
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-platform-service
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/study-platform-db
      DB_USERNAME: postgres
      DB_PASSWORD: root189065
      JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:

